name: Build
on: [push]
jobs:
  Build_Maven_Project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Java Environment
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Build Java Application
        run: mvn install verify
      - name: Test
        run: java -jar target/jb-hello-world-maven-0.2.0.jar
      - run: echo "üçè This job's status is ${{ job.status }}."